#!/usr/bin/env python

import sys

image_file = sys.argv[1]
sv_file = sys.argv[2]
name = sys.argv[3]

with open(image_file, 'r') as f:
    image = f.readline()
    split = image.split(',')
    with open(sv_file, 'w') as sv:
        """
        sv.write(f"logic [15:0] {name} [{len(split)}] = '{{\n")
        for i, pixel in enumerate(split):
            if i == len(split) - 1:
                sv.write(f"    'd{pixel}\n")
            else:
                sv.write(f"    'd{pixel},\n")
        sv.write("};")
        """
        sv.write(f"logic [15:0] {name} [{len(split)}];\n")
        for i, pixel in enumerate(split):
            sv.write(f"assign {name}[{i}] = 'd{pixel};\n")

