name: SimCommand CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
    - name: Install Verilator
      run: |
        sudo apt-get install -y verilator
        verilator --version
    - name: Build and Test
      run: ./mill simcommand.test -l IVerilog -l VCS -l org.scalatest.tags.Slow

